### PR TITLE
Jt article population holiday road

### PR DESCRIPTION
**Pull request by joetid09**
Merged with Devon's park updates. Have added my own eatery selection, selection now populate head and description for eatery article.

### CODE REVIEW

**Review by Devco2011 — CHANGES_REQUESTED** [review]
Please fix eateries.js line 22

**Review by TessaSoftEng — CHANGES_REQUESTED** [review]
Please fix SyntaxError: Invalid shorthand property initializer 5000/scripts/eateries/eatery.js:22

**Review by Devco2011 — APPROVED** [review]

**Review by TessaSoftEng — APPROVED** [review]
Error is gone, everything working now. Ok to merge.

**Review by Devco2011 — COMMENTED** [review]
Looks good

**Pull request merged**
